### ISSUE TITLE
CSS is not Complete

### ISSUE THREAD

**Issue by jasonballinger** [thejasonballinger-com/main#3]
The CSS under the file **styles.css** is currently incomplete. I am working on the GitHub Pages site, so it would be awesome if somebody could work on this for me. Thanks!

**Comment by jb-pi** [comment]
UPDATE:

For the **styles.css** file, a comment needs to be added to show what font faces are going to go to which type of text (headers & paragraphs). Also need to show which background colors to show, as well as text alignment.

**Comment by jasonballinger** [comment]
OK. Here are the font faces that are requested:

Haneli Fill for h1
Roboto for h2
Roboto for h3
Roboto for h4
Roboto Mono for h5
Roboto Mono for **code**
Roboto for h6

Roboto Slab for **p**

Those are the font faces requested. Somebody please claim the responsibility for changing the CSS Styles. @jb-pi is that OK for you?

**Comment by jb-pi** [comment]
Yes, that is OK. I will go ahead and let you know when I am done changing the font faces. Then you can close the issue.

**Comment by jasonballinger** [comment]
OK. Also, please center-align the text, background color should be **white** for the **body** right now.

**Comment by jasonballinger** [comment]
For **code**, please make the **text-align** left.

**Comment by jb-pi** [comment]
OK, all has been updated. I am finished and have committed the change to the master branch. The issue has now been completed. This issue can now be closed.

**Comment by jasonballinger** [comment]
OK, thanks for that @jb-pi !
*The issues has now been completed. It is now closed*
